import math

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

from classifiers import OneHotDataClassifierAdapter

CONT_FEATURES_GERMAN_CREDIT = ["duration", "credit_amount", "age"]
CONT_FEATURES_LENDING = ["emp_length", "annual_inc", "open_acc", "credit_years"]
CONT_FEATURES_COMPAS = ["age", "priors_count", "days_b_screening_arrest", "length_of_stay"]
CONT_FEATURES_ADULT = ["age", "hours-per-week"]


def prepare_output(model, cfs, test_item):
    """
    Prepare the explainer output in the required format.
    """

    # unpack test item
    record, label, pred, proba, target = test_item
    # prepare output
    list_new_probs = model.predict_proba(cfs)[:, 1]
    list_expl_full = cfs.reset_index(drop=True)
    list_expl_changes = []
    for _, cf in cfs.iterrows():
        changes = []
        for col in cfs.columns:
            if cf[col] != record[col]:
                changes.append(cf[col])
            else:
                changes.append("-")
        list_expl_changes.append(changes)
    list_expl_changes = pd.DataFrame(list_expl_changes, columns=cfs.columns)
    return {
        "record": record, "label": label, "pred": pred, "proba": proba, "target": target,
        "list_expl_full": list_expl_full,
        "list_expl_changes": list_expl_changes, "list_new_probs": pd.Series(list_new_probs),
    }

def immutable_features(num_features, cat_features, act_features, face_features):
    """
    Compute names of immutable features columns.
    """

    immutables, immutables_idx = [], []
    raw_immutables = ([f for f in num_features if f not in act_features] +
                      [f for f in cat_features if f not in act_features])
    for raw_feat in raw_immutables:
        cols = [c for c in face_features if c.startswith(raw_feat + "_")]
        immutables.extend(cols)
    immutables_idx = [face_features.index(f) for f in immutables]
    return immutables, immutables_idx

def compute_nbins(features, binning_process):
    """
    Compute number of bins.
    """

    n_bins = 0
    for f in features:
        n_bins += len(binning_process._binned_variables[f].splits)
    n_bins /= len(features)
    return n_bins


def compute_bounds(v):
    """
    Compute bounds.
    """

    v = v.strip("[]()'")
    lb, ub = v.split(",", 1)
    lb = lb.strip()
    ub = ub.strip()
    if lb != '-inf':
        lb = math.ceil(float(lb))
    if ub != 'inf':
        ub = math.floor(float(ub))
    return lb, ub


def rule_applies(x_cf, outer_if, inner_if, num_features):
    """
    Check if rule applies.
    """
    x_cf = x_cf.copy()
    for lit in (outer_if + inner_if):
        f, v = lit.split(" = ", 1)
        f, v = f.strip(), v.strip()
        if x_cf[f] != v:
            return False
    return True


def apply_then(x_cf, then, num_features):
    """
    Apply then rule.
    """
    x_cf = x_cf.copy()
    for lit in then:
        f, v = lit.split(" = ", 1)
        f, v = f.strip(), v.strip()
        x_cf[f] = v
    return x_cf


def bin_and_transform(x, binning_process, ohe):
    # x_bins = binning_process.transform(x, metric="bins")  # FIXME
    x_bins = x.copy()
    x_bins = x_bins.replace(r"np\.str_\((['\"].*?['\"])\)", r"\1", regex=True)
    x_oh = ohe.transform(x_bins)
    return pd.DataFrame(x_oh, columns=ohe.get_feature_names_out())


def analyze_results(results, facegroup, graph, feasibility_constraints_instance):
    """
    Analyze FACEGroup results.
    """

    dict = {}
    res = {str(key): value for key, value in results.items()}
    for key in res:
        if key in ["Node Connectivity", "Edge Connectivity", "Total coverage", "Graph Stats"]: continue
        res[key] = {str(k): v for k, v in res[key].items()}
        for factual in res[key]:
            if factual in ["Coverage", "Avg. distance", "Median distance", "Avg. path cost",
                           "Median path cost"]: continue
            shortest_paths_info, min_target_id = facegroup.compute_recourse(graph, int(factual),
                                                                            feasibility_constraints_instance, False)
            print("* Factual Point:", factual)
            if shortest_paths_info is not None and min_target_id is not None and shortest_paths_info != {}:
                print("	FACEGroup Info:")
                print(f"		CFE: {res[key][factual]['CFE_name']}")
                #print(f"		Shortest Path cost: {res[key][factual]['Shortest_path_cost']}")
                #print(f"		Shortest Path cost dist: {res[key][factual]['Shortest_paths_distance_cost']}")
                print(f"		Vector Distance: {res[key][factual]['Vector_distance']}")
            dict.update({int(factual): res[key][factual]['CFE_name']})
    return dict


def apply_rules_llm(record, rules, model):
    """
    Apply rules generated by the LLM and build the counterfactual.
    """
    from utils import clean_numpy2_strings

    cumulative_cfs, cumulative_cfs_final, cfs = record.copy(), [], []
    for rule in rules:
        cf = record.copy().to_frame().T
        for col, value in rule.items():
            value = model.binning_process_.get_binned_variable(col).transform([value], metric='bins')
            value = clean_numpy2_strings(pd.Series(value, index=[col]))
            value = value.values[0]
            if value == 'unknown':
                value = record[col]
            if value != record[col]:
                cf[col] = value
            if value != cumulative_cfs[col]:
                cumulative_cfs[col] = value
        if model.predict(cf.to_frame().T)[0] == 1:
            cfs.append(cf)
        if model.predict(cumulative_cfs.to_frame().T)[0] == 1 and len(cumulative_cfs_final) == 0:
            cumulative_cfs_final = cumulative_cfs.to_frame().T.copy()
    if len(cfs) > 0:
        cfs = pd.DataFrame(cfs)
    elif len(cumulative_cfs_final) > 0:
        cfs = cumulative_cfs_final
    return cfs


def prepare_data_face(df_train, features, target, model, num_features, cat_features, act_features):
    """
    Function to prepare data used in FACE and FACEGroup.
    """

    # prepare data
    ohe, model_ohe, X_oh, binning_process, y = prepare_data_ohe(df_train, features, target, model)
    # features passed to FACE and FACEGroup are all numeric
    face_features = list(ohe.get_feature_names_out())
    # define immutable features
    immutables, immutables_idx = immutable_features(num_features, cat_features, act_features, face_features)
    return ohe, model_ohe, X_oh, binning_process, y, face_features, immutables, immutables_idx


def prepare_data_ares_globece(features, act_features, df_train, target, model, dataset_name):
    """
    Function to prepare the data used in AReS and Globe-CE.
    """

    # define categorical, continuous and immutable features
    cat_features = features
    cont_features = []
    if dataset_name == "german-credit":
        # cont_features = CONT_FEATURES_GERMAN_CREDIT
        ...
    elif dataset_name == "lending":
        cont_features = CONT_FEATURES_LENDING
    elif dataset_name == "compas":
        cont_features = CONT_FEATURES_COMPAS
    elif dataset_name == "adult":
        cont_features = CONT_FEATURES_ADULT
    immutables = list(set(features) - set(act_features))
    # prepare data
    ohe, model_ohe, X_oh, binning_process, y = prepare_data_ohe(df_train, features, target, model)
    # define n_bins, dataset loader and model wrapper
    n_bins = compute_nbins(features, binning_process)
    return cat_features, cont_features, immutables, ohe, model_ohe, X_oh, binning_process, y, n_bins


def prepare_data_ohe(df_train, features, target, model):
    """
    prepare data using binning and one-hot encoding.
    """
    ohe_sep = '_'
    X, y = df_train[features], df_train[target]
    OHE = OneHotEncoder(sparse_output=False, drop=None, feature_name_combiner=lambda a, b: f"{a}{ohe_sep}{b}")  # feature_name_combiner?
    X_oh = OHE.fit_transform(X, y)
    X_oh = pd.DataFrame(X_oh, columns=OHE.get_feature_names_out(), index=X.index)
    model_oh = OneHotDataClassifierAdapter(model, OHE.get_feature_names_out(), ohe_sep)
    model_oh.fit(X_oh)
    bp = model.binning_process_  # for backward compatibility

    return OHE, model_oh, X_oh, bp, y
